import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :hermes, HermesWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

# No `force_ssl` here on purpose: it is a compile-time option, and the same
# image serves a LAN install over plain HTTP as well as a customer install
# behind a Cloudflare Tunnel. HTTPS is enforced at runtime instead, based on
# PHX_URL_SCHEME — see HermesWeb.Https and docs/adr/0005-https-zur-laufzeit.md.

# Configure Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Req

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
