defmodule HermesWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :hermes

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_hermes_key",
    signing_salt: "iWflpy71",
    same_site: "Lax"
  ]

  @doc """
  Session options without the parts that depend on the installation; see
  `HermesWeb.Https.session_options/0` for the ones actually used.
  """
  def base_session_options, do: @session_options

  # The session options are decided at runtime (the Secure flag depends on
  # whether this installation runs behind TLS).
  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: {HermesWeb.Https, :session_options, []}]],
    longpoll: [connect_info: [session: {HermesWeb.Https, :session_options, []}]]

  # Redirects to https where this installation runs behind TLS; does nothing
  # in a LAN or Tailscale install (see HermesWeb.Https).
  plug HermesWeb.Https

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :hermes,
    gzip: not code_reloading?,
    only: HermesWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :hermes
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug :session
  plug HermesWeb.Router

  defp session(conn, _opts) do
    Plug.Session.call(conn, Plug.Session.init(HermesWeb.Https.session_options()))
  end
end
